USE [master]
GO

IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'FeedbackUser')
BEGIN
    DROP LOGIN [FeedbackUser]
END

CREATE LOGIN [FeedbackUser] WITH PASSWORD=N'Gv20QhJWdsSu4NPyIV3oNDrCJczItexRf98lSZdcH70=', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [FeedbackUser]
GO